using ScarletWitch.Sap_ArrowAndBranchWinery.Domain;

namespace ApiToScarletWitchMapper
{
	public partial class Mapper
	{
		public virtual ChartOfAccount ToSql(Sap.Api.Domain.ChartOfAccounts.ChartOfAccount x)
		{
			return new ChartOfAccount {
				Balance = x.Balance,
				BalanceFrgnCurr = x.BalanceFrgnCurr,
				BalanceSyscurr = x.BalanceSyscurr,
				AccountLevel = x.AccountLevel,
				InternalReconNo = x.InternalReconNo,
				AccountPurposeCode = x.AccountPurposeCode,
				AccountType = x.AccountType,
				AcctCurrency = x.AcctCurrency,
				ActiveAccount = x.ActiveAccount,
				AllowChangeVatGroup = x.AllowChangeVatGroup,
				AllowMultipleLinking = x.AllowMultipleLinking,
				BlockManualPosting = x.BlockManualPosting,
				BPLID = x.BPLID,
				BPLName = x.BPLName,
				BudgetAccount = x.BudgetAccount,
				CashAccount = x.CashAccount,
				CashFlowRelevant = x.CashFlowRelevant,
				Category = x.Category,
				Code = x.Code,
				CostAccountingOnly = x.CostAccountingOnly,
				CostElementCode = x.CostElementCode,
				CostElementRelevant = x.CostElementRelevant,
				DataExportCode = x.DataExportCode,
				DatevAccount = x.DatevAccount,
				DatevAutoAccount = x.DatevAutoAccount,
				DatevFirstDataEntry = x.DatevFirstDataEntry,
				DefaultVatGroup = x.DefaultVatGroup,
				Details = x.Details,
				DistributionRule2Relevant = x.DistributionRule2Relevant,
				DistributionRule3Relevant = x.DistributionRule3Relevant,
				DistributionRule4Relevant = x.DistributionRule4Relevant,
				DistributionRule5Relevant = x.DistributionRule5Relevant,
				DistributionRuleRelevant = x.DistributionRuleRelevant,
				ExpenseClassificationCategory = x.ExpenseClassificationCategory,
				ExpenseClassificationType = x.ExpenseClassificationType,
				ExternalCode = x.ExternalCode,
				ExternalReconNo = x.ExternalReconNo,
				FatherAccountKey = x.FatherAccountKey,
				ForeignName = x.ForeignName,
				FormatCode = x.FormatCode,
				FrozenFor = x.FrozenFor,
				FrozenFrom = x.FrozenFrom,
				FrozenRemarks = x.FrozenRemarks,
				FrozenTo = x.FrozenTo,
				IncomeClassificationCategory = x.IncomeClassificationCategory,
				IncomeClassificationType = x.IncomeClassificationType,
				LiableForAdvances = x.LiableForAdvances,
				LoadingFactorCode = x.LoadingFactorCode,
				LoadingFactorCode2 = x.LoadingFactorCode2,
				LoadingFactorCode3 = x.LoadingFactorCode3,
				LoadingFactorCode4 = x.LoadingFactorCode4,
				LoadingFactorCode5 = x.LoadingFactorCode5,
				LoadingType = x.LoadingType,
				LockManualTransaction = x.LockManualTransaction,
				Name = x.Name,
				OfficialAccountCode = x.OfficialAccountCode,
				PCN874ReportRelevant = x.PCN874ReportRelevant,
				PlanningLevel = x.PlanningLevel,
				PrimaryAccount = x.PrimaryAccount,
				PrimaryClosingAccount = x.PrimaryClosingAccount,
				ProjectCode = x.ProjectCode,
				ProjectRelevant = x.ProjectRelevant,
				Protected = x.Protected,
				RateConversion = x.RateConversion,
				ReconciledAccount = x.ReconciledAccount,
				ReferentialAccountCode = x.ReferentialAccountCode,
				RevaluationCoordinated = x.RevaluationCoordinated,
				StandardAccountCode = x.StandardAccountCode,
				TaxExemptAccount = x.TaxExemptAccount,
				TaxLiableAccount = x.TaxLiableAccount,
				TaxonomyCode = x.TaxonomyCode,
				TransactionCode = x.TransactionCode,
				ValidFor = x.ValidFor,
				ValidFrom = x.ValidFrom,
				ValidRemarks = x.ValidRemarks,
				ValidTo = x.ValidTo,
				VATRegNum = x.VATRegNum,
			};
		}
	}
}