using ScarletWitch.Sap_ArrowAndBranchWinery.Domain;

namespace ApiToScarletWitchMapper
{
	public partial class Mapper
	{
		public virtual IncomingPayment ToSql(Sap.Core.Domain.IncomingPayments.IncomingPayment x)
		{
			return new IncomingPayment {
				DocEntry = x.DocEntry,
				DocNum = x.DocNum,
				Series = x.Series,
				DocDate = x.DocDate,
				DueDate = x.DueDate,
				TaxDate = x.TaxDate,
				TransferDate = x.TransferDate,
				VatDate = x.VatDate,
				BankChargeAmount = x.BankChargeAmount,
				BankChargeAmountInFC = x.BankChargeAmountInFC,
				BankChargeAmountInSC = x.BankChargeAmountInSC,
				BillOfExchangeAmount = x.BillOfExchangeAmount,
				BillOfExchangeAmountFC = x.BillOfExchangeAmountFC,
				BillOfExchangeAmountSC = x.BillOfExchangeAmountSC,
				CashSum = x.CashSum,
				CashSumFC = x.CashSumFC,
				CashSumSys = x.CashSumSys,
				DeductionPercent = x.DeductionPercent,
				DeductionSum = x.DeductionSum,
				DiscountPercent = x.DiscountPercent,
				DocRate = x.DocRate,
				TransferRealAmount = x.TransferRealAmount,
				TransferSum = x.TransferSum,
				UnderOverpaymentdifference = x.UnderOverpaymentdifference,
				UnderOverpaymentdiffFC = x.UnderOverpaymentdiffFC,
				UnderOverpaymentdiffSC = x.UnderOverpaymentdiffSC,
				WTAmount = x.WTAmount,
				WTAmountFC = x.WTAmountFC,
				WTAmountSC = x.WTAmountSC,
				WtBaseSum = x.WtBaseSum,
				WtBaseSumFC = x.WtBaseSumFC,
				WtBaseSumSC = x.WtBaseSumSC,
				WTTaxableAmount = x.WTTaxableAmount,
				Address = x.Address,
				ApplyVAT = x.ApplyVAT,
				AttachmentEntry = x.AttachmentEntry,
				AuthorizationStatus = x.AuthorizationStatus,
				BankAccount = x.BankAccount,
				BankCode = x.BankCode,
				BillOfExchangeAgent = x.BillOfExchangeAgent,
				BillofExchangeStatus = x.BillofExchangeStatus,
				BlanketAgreement = x.BlanketAgreement,
				BoeAccount = x.BoeAccount,
				BPLID = x.BPLID,
				BPLName = x.BPLName,
				Cancelled = x.Cancelled,
				CardCode = x.CardCode,
				CardName = x.CardName,
				CashAccount = x.CashAccount,
				CertificationNumber = x.CertificationNumber,
				CheckAccount = x.CheckAccount,
				Cig = x.Cig,
				ContactPersonCode = x.ContactPersonCode,
				ControlAccount = x.ControlAccount,
				CounterReference = x.CounterReference,
				Cup = x.Cup,
				CurrencyIsLocal = x.CurrencyIsLocal,
				DocCurrency = x.DocCurrency,
				DocObjectCode = x.DocObjectCode,
				DocType = x.DocType,
				DocTypte = x.DocTypte,
				EDocExportFormat = x.EDocExportFormat,
				ElecCommMessage = x.ElecCommMessage,
				ElecCommStatus = x.ElecCommStatus,
				HandWritten = x.HandWritten,
				IsPayToBank = x.IsPayToBank,
				JournalRemarks = x.JournalRemarks,
				LocalCurrency = x.LocalCurrency,
				LocationCode = x.LocationCode,
				PaymentByWTCertif = x.PaymentByWTCertif,
				PaymentPriority = x.PaymentPriority,
				PaymentType = x.PaymentType,
				PayToBankAccountNo = x.PayToBankAccountNo,
				PayToBankBranch = x.PayToBankBranch,
				PayToBankCode = x.PayToBankCode,
				PayToBankCountry = x.PayToBankCountry,
				PayToCode = x.PayToCode,
				Printed = x.Printed,
				PrivateKeyVersion = x.PrivateKeyVersion,
				Proforma = x.Proforma,
				ProjectCode = x.ProjectCode,
				Reference1 = x.Reference1,
				Reference2 = x.Reference2,
				Remarks = x.Remarks,
				SignatureDigest = x.SignatureDigest,
				SignatureInputMessage = x.SignatureInputMessage,
				SplitTransaction = x.SplitTransaction,
				SplitVendorCreditRow = x.SplitVendorCreditRow,
				TaxGroup = x.TaxGroup,
				TransactionCode = x.TransactionCode,
				TransferAccount = x.TransferAccount,
				TransferReference = x.TransferReference,
				VATRegNum = x.VATRegNum,
				WTAccount = x.WTAccount,
				WTCode = x.WTCode,
			};
		}
	}
}