using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Sap.Api.Domain.Common;
using Sap.Core;
using Sap.Core.Http;

namespace Sap.Api.Domain.PurchaseOrders
{
	public partial class PurchaseOrder : BaseEntity
	{
		#region Fields
		public AddressExtension AddressExtension;
		public DateTime? CreationDate;
		public DateTime? DocDate;
		public DateTime? DocDueDate;
		public DateTime? TaxDate;
		public DateTime? UpdateDate;
		public decimal? BaseAmount;
		public decimal? BaseAmountFC;
		public decimal? BaseAmountSC;
		public decimal? DiscountPercent;
		public decimal? DocRate;
		public decimal? DocTotal;
		public decimal? DocTotalFc;
		public decimal? DocTotalSys;
		public decimal? DownPayment;
		public decimal? DownPaymentAmount;
		public decimal? DownPaymentAmountFC;
		public decimal? DownPaymentAmountSC;
		public decimal? DownPaymentPercentage;
		public decimal? RoundingDiffAmount;
		public decimal? RoundingDiffAmountFC;
		public decimal? RoundingDiffAmountSC;
		public decimal? TotalDiscount;
		public decimal? TotalDiscountFC;
		public decimal? TotalDiscountSC;
		public decimal? TotalEqualizationTax;
		public decimal? TotalEqualizationTaxFC;
		public decimal? TotalEqualizationTaxSC;
		public decimal? VatPercent;
		public decimal? VatSum;
		public decimal? VatSumFc;
		public decimal? VatSumSys;
		public decimal? WTAmount;
		public decimal? WTAmountFC;
		public decimal? WTAmountSC;
		public decimal? WTApplied;
		public decimal? WTAppliedFC;
		public decimal? WTAppliedSC;
		public decimal? WTExemptedAmount;
		public decimal? WTExemptedAmountFC;
		public decimal? WTExemptedAmountSC;
		public decimal? WTNonSubjectAmount;
		public decimal? WTNonSubjectAmountFC;
		public decimal? WTNonSubjectAmountSC;
		public IList<DocumentLine> DocumentLines;
		public IList<object> DocumentAdditionalExpenses;
		public IList<object> DocumentApprovalRequests;
		public IList<object> DocumentReferences;
		public IList<object> DocumentSpecialLines;
		public IList<object> ElectronicProtocols;
		public IList<object> WithholdingTaxDataCollection;
		public IList<object> WithholdingTaxDataWTXCollection;
		public int? CashDiscountDateOffset;
		public int? ContactPersonCode;
		public int? DataVersion;
		public int? DocEntry;
		public int? DocNum;
		public int? ExtraDays;
		public int? ExtraMonth;
		public int? FinancialPeriod;
		public int? LanguageCode;
		public int? NumberOfInstallments;
		public int? PaymentGroupCode;
		public int? RelatedType;
		public int? SalesPersonCode;
		public int? Segment;
		public int? Series;
		public int? TransportationCode;
		public int? UserSign;
		public string AddLegIn;
		public string Address;
		public string Address2;
		public string AgentCode;
		public string AnnualInvoiceDeclarationReference;
		public string ApplyCurrentVATRatesForDownPaymentsToDraw;
		public string ApplyTaxOnFirstInstallment;
		public string ArchiveNonremovableSalesQuotation;
		public string AssetValueDate;
		public string ATDocumentType;
		public string AttachmentEntry;
		public string AuthorizationCode;
		public string AuthorizationStatus;
		public string BillOfExchangeReserved;
		public string BlanketAgreementNumber;
		public string BlockDunning;
		public string Box1099;
		public string BPChannelCode;
		public string BPChannelContact;
		public string BPLIDAssignedToInvoice;
		public string BPLName;
		public string CancelDate;
		public string Cancelled;
		public string CancelStatus;
		public string CardCode;
		public string CardName;
		public string CentralBankIndicator;
		public string CertificationNumber;
		public string Cig;
		public string ClosingDate;
		public string ClosingOption;
		public string ClosingRemarks;
		public string Comments;
		public string CommissionTrade;
		public string CommissionTradeReturn;
		public string Confirmed;
		public string ControlAccount;
		public string CreateOnlineQuotation;
		public string CreateQRCodeFrom;
		public string Cup;
		public string CustOffice;
		public string DANFELgTxt;
		public string DateOfReportingControlStatementVAT;
		public string DeferredTax;
		public string DocCurrency;
		public string DocObjectCode;
		public string DocTime;
		public string DocType;
		public string DocumentDelivery;
		public string DocumentsOwner;
		public string DocumentStatus;
		public string DocumentSubType;
		public string DocumentTaxID;
		public string DownPaymentStatus;
		public string DownPaymentType;
		public string EDocErrorCode;
		public string EDocErrorMessage;
		public string EDocExportFormat;
		public string EDocGenerationType;
		public string EDocNum;
		public string EDocSeries;
		public string EDocStatus;
		public string ElecCommMessage;
		public string ElecCommStatus;
		public string EndDeliveryDate;
		public string EndDeliveryTime;
		public string ETaxNumber;
		public string ETaxWebSite;
		public string ExcludeFromTaxReportControlStatementVAT;
		public string ExemptionValidityDateFrom;
		public string ExemptionValidityDateTo;
		public string ExternalCorrectedDocNum;
		public string FatherCard;
		public string FatherType;
		public string FCI;
		public string FederalTaxID;
		public string FiscalDocNum;
		public string FolioNumber;
		public string FolioNumberFrom;
		public string FolioNumberTo;
		public string FolioPrefixString;
		public string Form1099;
		public string GroupHandWritten;
		public string GroupNumber;
		public string GroupSeries;
		public string GTSChecker;
		public string GTSPayee;
		public string HandWritten;
		public string ImportFileNum;
		public string Indicator;
		public string InsuranceOperation347;
		public string InterimType;
		public string InternalCorrectedDocNum;
		public string InventoryStatus;
		public string IsAlteration;
		public string IsPayToBank;
		public string JournalMemo;
		public string LastPageFolioNumber;
		public string LegTextF;
		public string Letter;
		public string ManualNumber;
		public string MaximumCashDiscount;
		public string NetProcedure;
		public string NextCorrectingDocument;
		public string NotRelevantForMonthlyInvoice;
		public string NTSApproved;
		public string NTSApprovedNumber;
		public string NumAtCard;
		[JsonProperty("odata.etag")]
		public string OdataEtag;
		public string OpenForLandedCosts;
		public string OpeningRemarks;
		public string PartialSupply;
		public string PaymentBlock;
		public string PaymentBlockEntry;
		public string PaymentMethod;
		public string PaymentReference;
		public string PayToBankAccountNo;
		public string PayToBankBranch;
		public string PayToBankCode;
		public string PayToBankCountry;
		public string PayToCode;
		public string PeriodIndicator;
		public string Pick;
		public string PickRemark;
		public string PickStatus;
		public string PlasticPackagingTaxRelevant;
		public string PointOfIssueCode;
		public string POSCashierNumber;
		public string POSCashRegister;
		public string POSDailySummaryNo;
		public string POSEquipmentNumber;
		public string POSManufacturerSerialNumber;
		public string POSReceiptNo;
		public string PriceMode;
		public string Printed;
		public string PrintSEPADirect;
		public string PrivateKeyVersion;
		public string Project;
		public string Receiver;
		public string Reference1;
		public string Reference2;
		public string RelatedEntry;
		public string Releaser;
		public string RelevantToGTS;
		public string ReopenManuallyClosedOrCanceledDocument;
		public string ReopenOriginalDocument;
		public string ReportingSectionControlStatementVAT;
		public string RequriedDate;
		public string Reserve;
		public string ReserveInvoice;
		public string ReuseDocumentNum;
		public string ReuseNotaFiscalNum;
		public string RevisionPo;
		public string Rounding;
		public string SAPPassport;
		public string SequenceCode;
		public string SequenceModel;
		public string SequenceSerial;
		public string SeriesString;
		public string ServiceGrossProfitPercent;
		public string ShipFrom;
		public string ShipPlace;
		public string ShipState;
		public string ShipToCode;
		public string ShowSCN;
		public string SignatureDigest;
		public string SignatureInputMessage;
		public string SpecifiedClosingDate;
		public string StartDeliveryDate;
		public string StartDeliveryTime;
		public string StartFrom;
		public string Submitted;
		public string SubSeriesString;
		public string SummeryType;
		public string Supplier;
		public string TaxExemptionLetterNum;
		public string TaxOnInstallments;
		public string TrackingNumber;
		public string TransNum;
		public string UpdateTime;
		public string UseBillToAddrToDetermineTax;
		public string UseCorrectionVATGroup;
		public string UseShpdGoodsAct;
		public string VatDate;
		public string VATRegNum;
		public string VehiclePlate;
		public string WareHouseUpdateType;
		public TaxExtension TaxExtension;
		#endregion

		public PurchaseOrder()
		{
			AddressExtension = new AddressExtension();
			DocumentLines = new List<DocumentLine>();
			DocumentAdditionalExpenses = new List<object>();
			DocumentApprovalRequests = new List<object>();
			DocumentReferences = new List<object>();
			DocumentSpecialLines = new List<object>();
			ElectronicProtocols = new List<object>();
			WithholdingTaxDataCollection = new List<object>();
			WithholdingTaxDataWTXCollection = new List<object>();
			TaxExtension = new TaxExtension();
		}
	}
}