using ScarletWitch.Sap_ArrowAndBranchWinery.Domain;

namespace ApiToScarletWitchMapper
{
	public partial class Mapper
	{
		public virtual JournalEntry ToSql(Sap.Api.Domain.JournalEntries.JournalEntry x)
		{
			return new JournalEntry {
				JdtNum = x.JdtNum,
				Number = x.Number,
				Original = x.Original,
				Series = x.Series,
				DueDate = x.DueDate,
				ReferenceDate = x.ReferenceDate,
				TaxDate = x.TaxDate,
				WTSum = x.WTSum,
				WTSumFC = x.WTSumFC,
				WTSumSC = x.WTSumSC,
				AdjustTransaction = x.AdjustTransaction,
				AllocationNumberIL = x.AllocationNumberIL,
				AttachmentEntry = x.AttachmentEntry,
				AutomaticWT = x.AutomaticWT,
				AutoVAT = x.AutoVAT,
				BaseReference = x.BaseReference,
				BlanketAgreementNumber = x.BlanketAgreementNumber,
				BlockDunningLetter = x.BlockDunningLetter,
				CertificationNumber = x.CertificationNumber,
				Cig = x.Cig,
				Corisptivi = x.Corisptivi,
				Cup = x.Cup,
				DeferredTax = x.DeferredTax,
				DocumentType = x.DocumentType,
				ECDPostingType = x.ECDPostingType,
				ExcludeFromTaxReportControlStatementVAT = x.ExcludeFromTaxReportControlStatementVAT,
				ExposedTransNumber = x.ExposedTransNumber,
				FolioNumber = x.FolioNumber,
				FolioNumberFrom = x.FolioNumberFrom,
				FolioNumberTo = x.FolioNumberTo,
				FolioPrefixString = x.FolioPrefixString,
				Indicator = x.Indicator,
				IsCostCenterTransfer = x.IsCostCenterTransfer,
				Letter = x.Letter,
				LocationCode = x.LocationCode,
				Memo = x.Memo,
				OperationCode = x.OperationCode,
				OriginalJournal = x.OriginalJournal,
				PointOfIssueCode = x.PointOfIssueCode,
				Printed = x.Printed,
				PrivateKeyVersion = x.PrivateKeyVersion,
				ProjectCode = x.ProjectCode,
				Reference = x.Reference,
				Reference2 = x.Reference2,
				Reference3 = x.Reference3,
				Report347 = x.Report347,
				ReportEU = x.ReportEU,
				ReportingSectionControlStatementVAT = x.ReportingSectionControlStatementVAT,
				ResidenceNumberType = x.ResidenceNumberType,
				SAFTTransactionType = x.SAFTTransactionType,
				SAPPassport = x.SAPPassport,
				SignatureDigest = x.SignatureDigest,
				SignatureInputMessage = x.SignatureInputMessage,
				StampTax = x.StampTax,
				StornoDate = x.StornoDate,
				TransactionCode = x.TransactionCode,
				UseAutoStorno = x.UseAutoStorno,
				VatDate = x.VatDate,
			};
		}

		public virtual JournalEntryLine ToSql(Sap.Api.Domain.JournalEntries.JournalEntryLine x)
		{
			return new JournalEntryLine {
				JdtNum = x.JdtNum,
				LineID = x.LineID,
				AccountCode = x.AccountCode,
				Debit = x.Debit,
				Credit = x.Credit,
				FCDebit = x.FCDebit,
				FCCredit = x.FCCredit,
				FCCurrency = x.FCCurrency,
				DueDate = x.DueDate,
				ShortName = x.ShortName,
				ContraAccount = x.ContraAccount,
				LineMemo = x.LineMemo,
				ReferenceDate1 = x.ReferenceDate1,
				ReferenceDate2 = x.ReferenceDate2,
				Reference1 = x.Reference1,
				Reference2 = x.Reference2,
				ProjectCode = x.ProjectCode,
				CostingCode = x.CostingCode,
				TaxDate = x.TaxDate,
				BaseSum = x.BaseSum,
				TaxGroup = x.TaxGroup,
				DebitSys = x.DebitSys,
				CreditSys = x.CreditSys,
				VatDate = x.VatDate,
				VatLine = x.VatLine,
				SystemBaseAmount = x.SystemBaseAmount,
				VatAmount = x.VatAmount,
				SystemVatAmount = x.SystemVatAmount,
				GrossValue = x.GrossValue,
				AdditionalReference = x.AdditionalReference,
				CheckAbs = x.CheckAbs,
				CostingCode2 = x.CostingCode2,
				CostingCode3 = x.CostingCode3,
				CostingCode4 = x.CostingCode4,
				TaxCode = x.TaxCode,
				TaxPostAccount = x.TaxPostAccount,
				CostingCode5 = x.CostingCode5,
				LocationCode = x.LocationCode,
				ControlAccount = x.ControlAccount,
				EqualizationTaxAmount = x.EqualizationTaxAmount,
				SystemEqualizationTaxAmount = x.SystemEqualizationTaxAmount,
				TotalTax = x.TotalTax,
				SystemTotalTax = x.SystemTotalTax,
				WTLiable = x.WTLiable,
				WTRow = x.WTRow,
				PaymentBlock = x.PaymentBlock,
				BlockReason = x.BlockReason,
				FederalTaxID = x.FederalTaxID,
				BPLID = x.BPLID,
				BPLName = x.BPLName,
				VATRegNum = x.VATRegNum,
				PaymentOrdered = x.PaymentOrdered,
				ExposedTransNumber = x.ExposedTransNumber,
				DocumentArray = x.DocumentArray,
				DocumentLine = x.DocumentLine,
				CostElementCode = x.CostElementCode,
				Cig = x.Cig,
				Cup = x.Cup,
				IncomeClassificationCategory = x.IncomeClassificationCategory,
				IncomeClassificationType = x.IncomeClassificationType,
				ExpensesClassificationCategory = x.ExpensesClassificationCategory,
				ExpensesClassificationType = x.ExpensesClassificationType,
				VATClassificationCategory = x.VATClassificationCategory,
				VATClassificationType = x.VATClassificationType,
				VATExemptionCause = x.VATExemptionCause,
			};
		}
	}
}