using Sap.Core.Domain.Common;

namespace Sap.Core.Domain.IncomingPayments
{
	public partial class IncomingPaymentRequest : BaseRequest
	{
		#region Fields
		public const string ACTION = "IncomingPayments";
		public BillOfExchange BillOfExchange;
		public DateTime? DocDate;
		public DateTime? DueDate;
		public DateTime? TaxDate;
		public DateTime? TransferDate;
		public DateTime? VatDate;
		public double? BankChargeAmount;
		public double? BankChargeAmountInFC;
		public double? BankChargeAmountInSC;
		public double? BillOfExchangeAmount;
		public double? BillOfExchangeAmountFC;
		public double? BillOfExchangeAmountSC;
		public double? CashSum;
		public double? CashSumFC;
		public double? CashSumSys;
		public double? DeductionPercent;
		public double? DeductionSum;
		public double? DiscountPercent;
		public double? DocRate;
		public double? TransferRealAmount;
		public double? TransferSum;
		public double? UnderOverpaymentdifference;
		public double? UnderOverpaymentdiffFC;
		public double? UnderOverpaymentdiffSC;
		public double? WTAmount;
		public double? WTAmountFC;
		public double? WTAmountSC;
		public double? WtBaseSum;
		public double? WtBaseSumFC;
		public double? WtBaseSumSC;
		public double? WTTaxableAmount;
		public IList<CashFlowAssignment> CashFlowAssignments;
		public IList<object> ElectronicProtocols;
		public IList<object> PaymentAccounts;
		public IList<object> PaymentChecks;
		public IList<object> PaymentCreditCards;
		public IList<object> PaymentsApprovalRequests;
		public IList<object> WithholdingTaxCertificatesCollection;
		public IList<object> WithholdingTaxDataWTXCollection;
		public IList<PaymentDocumentReferencesCollection> PaymentDocumentReferencesCollection;
		public IList<PaymentInvoice> PaymentInvoices;
		public int? DocEntry;
		public int? DocNum;
		public int? Series;
		public string? Address;
		public string? ApplyVAT;
		public string? AttachmentEntry;
		public string? AuthorizationStatus;
		public string? BankAccount;
		public string? BankCode;
		public string? BillOfExchangeAgent;
		public string? BillofExchangeStatus;
		public string? BlanketAgreement;
		public string? BoeAccount;
		public string? BPLID;
		public string? BPLName;
		public string? Cancelled;
		public string? CardCode;
		public string? CardName;
		public string? CashAccount;
		public string? CertificationNumber;
		public string? CheckAccount;
		public string? Cig;
		public string? ContactPersonCode;
		public string? ControlAccount;
		public string? CounterReference;
		public string? Cup;
		public string? CurrencyIsLocal;
		public string? DocCurrency;
		public string? DocObjectCode;
		public string? DocType;
		public string? DocTypte;
		public string? EDocExportFormat;
		public string? ElecCommMessage;
		public string? ElecCommStatus;
		public string? HandWritten;
		public string? IsPayToBank;
		public string? JournalRemarks;
		public string? LocalCurrency;
		public string? LocationCode;
		public string? PaymentByWTCertif;
		public string? PaymentPriority;
		public string? PaymentType;
		public string? PayToBankAccountNo;
		public string? PayToBankBranch;
		public string? PayToBankCode;
		public string? PayToBankCountry;
		public string? PayToCode;
		public string? Printed;
		public string? PrivateKeyVersion;
		public string? Proforma;
		public string? ProjectCode;
		public string? Reference1;
		public string? Reference2;
		public string? Remarks;
		public string? SignatureDigest;
		public string? SignatureInputMessage;
		public string? SplitTransaction;
		public string? SplitVendorCreditRow;
		public string? TaxGroup;
		public string? TransactionCode;
		public string? TransferAccount;
		public string? TransferReference;
		public string? VATRegNum;
		public string? WTAccount;
		public string? WTCode;
		#endregion

		public IncomingPaymentRequest()
		{
			BillOfExchange = new BillOfExchange();
			CashFlowAssignments = new List<CashFlowAssignment>();
			ElectronicProtocols = new List<object>();
			PaymentAccounts = new List<object>();
			PaymentChecks = new List<object>();
			PaymentCreditCards = new List<object>();
			PaymentsApprovalRequests = new List<object>();
			WithholdingTaxCertificatesCollection = new List<object>();
			WithholdingTaxDataWTXCollection = new List<object>();
			PaymentDocumentReferencesCollection = new List<PaymentDocumentReferencesCollection>();
			PaymentInvoices = new List<PaymentInvoice>();
		}

		public IncomingPaymentRequest(int docEntry)
		{
			DocEntry = docEntry;
			BillOfExchange = new BillOfExchange();
			CashFlowAssignments = new List<CashFlowAssignment>();
			ElectronicProtocols = new List<object>();
			PaymentAccounts = new List<object>();
			PaymentChecks = new List<object>();
			PaymentCreditCards = new List<object>();
			PaymentsApprovalRequests = new List<object>();
			WithholdingTaxCertificatesCollection = new List<object>();
			WithholdingTaxDataWTXCollection = new List<object>();
			PaymentDocumentReferencesCollection = new List<PaymentDocumentReferencesCollection>();
			PaymentInvoices = new List<PaymentInvoice>();
		}

		public IncomingPaymentRequest(IncomingPayment x)
		{
			BillOfExchange = x.BillOfExchange;
			DocDate = x.DocDate;
			DueDate = x.DueDate;
			TaxDate = x.TaxDate;
			TransferDate = x.TransferDate;
			VatDate = x.VatDate;
			BankChargeAmount = x.BankChargeAmount;
			BankChargeAmountInFC = x.BankChargeAmountInFC;
			BankChargeAmountInSC = x.BankChargeAmountInSC;
			BillOfExchangeAmount = x.BillOfExchangeAmount;
			BillOfExchangeAmountFC = x.BillOfExchangeAmountFC;
			BillOfExchangeAmountSC = x.BillOfExchangeAmountSC;
			CashSum = x.CashSum;
			CashSumFC = x.CashSumFC;
			CashSumSys = x.CashSumSys;
			DeductionPercent = x.DeductionPercent;
			DeductionSum = x.DeductionSum;
			DiscountPercent = x.DiscountPercent;
			DocRate = x.DocRate;
			TransferRealAmount = x.TransferRealAmount;
			TransferSum = x.TransferSum;
			UnderOverpaymentdifference = x.UnderOverpaymentdifference;
			UnderOverpaymentdiffFC = x.UnderOverpaymentdiffFC;
			UnderOverpaymentdiffSC = x.UnderOverpaymentdiffSC;
			WTAmount = x.WTAmount;
			WTAmountFC = x.WTAmountFC;
			WTAmountSC = x.WTAmountSC;
			WtBaseSum = x.WtBaseSum;
			WtBaseSumFC = x.WtBaseSumFC;
			WtBaseSumSC = x.WtBaseSumSC;
			WTTaxableAmount = x.WTTaxableAmount;
			CashFlowAssignments = x.CashFlowAssignments;
			ElectronicProtocols = x.ElectronicProtocols;
			PaymentAccounts = x.PaymentAccounts;
			PaymentChecks = x.PaymentChecks;
			PaymentCreditCards = x.PaymentCreditCards;
			PaymentsApprovalRequests = x.PaymentsApprovalRequests;
			WithholdingTaxCertificatesCollection = x.WithholdingTaxCertificatesCollection;
			WithholdingTaxDataWTXCollection = x.WithholdingTaxDataWTXCollection;
			PaymentDocumentReferencesCollection = x.PaymentDocumentReferencesCollection;
			PaymentInvoices = x.PaymentInvoices;
			DocEntry = x.DocEntry;
			DocNum = x.DocNum;
			Series = x.Series;
			Address = x.Address;
			ApplyVAT = x.ApplyVAT;
			AttachmentEntry = x.AttachmentEntry;
			AuthorizationStatus = x.AuthorizationStatus;
			BankAccount = x.BankAccount;
			BankCode = x.BankCode;
			BillOfExchangeAgent = x.BillOfExchangeAgent;
			BillofExchangeStatus = x.BillofExchangeStatus;
			BlanketAgreement = x.BlanketAgreement;
			BoeAccount = x.BoeAccount;
			BPLID = x.BPLID;
			BPLName = x.BPLName;
			Cancelled = x.Cancelled;
			CardCode = x.CardCode;
			CardName = x.CardName;
			CashAccount = x.CashAccount;
			CertificationNumber = x.CertificationNumber;
			CheckAccount = x.CheckAccount;
			Cig = x.Cig;
			ContactPersonCode = x.ContactPersonCode;
			ControlAccount = x.ControlAccount;
			CounterReference = x.CounterReference;
			Cup = x.Cup;
			CurrencyIsLocal = x.CurrencyIsLocal;
			DocCurrency = x.DocCurrency;
			DocObjectCode = x.DocObjectCode;
			DocType = x.DocType;
			DocTypte = x.DocTypte;
			EDocExportFormat = x.EDocExportFormat;
			ElecCommMessage = x.ElecCommMessage;
			ElecCommStatus = x.ElecCommStatus;
			HandWritten = x.HandWritten;
			IsPayToBank = x.IsPayToBank;
			JournalRemarks = x.JournalRemarks;
			LocalCurrency = x.LocalCurrency;
			LocationCode = x.LocationCode;
			PaymentByWTCertif = x.PaymentByWTCertif;
			PaymentPriority = x.PaymentPriority;
			PaymentType = x.PaymentType;
			PayToBankAccountNo = x.PayToBankAccountNo;
			PayToBankBranch = x.PayToBankBranch;
			PayToBankCode = x.PayToBankCode;
			PayToBankCountry = x.PayToBankCountry;
			PayToCode = x.PayToCode;
			Printed = x.Printed;
			PrivateKeyVersion = x.PrivateKeyVersion;
			Proforma = x.Proforma;
			ProjectCode = x.ProjectCode;
			Reference1 = x.Reference1;
			Reference2 = x.Reference2;
			Remarks = x.Remarks;
			SignatureDigest = x.SignatureDigest;
			SignatureInputMessage = x.SignatureInputMessage;
			SplitTransaction = x.SplitTransaction;
			SplitVendorCreditRow = x.SplitVendorCreditRow;
			TaxGroup = x.TaxGroup;
			TransactionCode = x.TransactionCode;
			TransferAccount = x.TransferAccount;
			TransferReference = x.TransferReference;
			VATRegNum = x.VATRegNum;
			WTAccount = x.WTAccount;
			WTCode = x.WTCode;
		}
	}
}