using ScarletWitch.Sap_ArrowAndBranchRareCoins.Domain;

namespace Sap.ApiToScarAabrcMapper
{
	public partial class Mapper
	{
		public virtual AddressExtension ToSql(Api.Domain.Common.AddressExtension x)
		{
			return new AddressExtension {
				DocEntry = x.DocEntry,
				BillToAddress2 = x.BillToAddress2,
				BillToAddress3 = x.BillToAddress3,
				BillToAddressType = x.BillToAddressType,
				BillToBlock = x.BillToBlock,
				BillToBuilding = x.BillToBuilding,
				BillToCity = x.BillToCity,
				BillToCountry = x.BillToCountry,
				BillToCounty = x.BillToCounty,
				BillToGlobalLocationNumber = x.BillToGlobalLocationNumber,
				BillToState = x.BillToState,
				BillToStreet = x.BillToStreet,
				BillToStreetNo = x.BillToStreetNo,
				BillToZipCode = x.BillToZipCode,
				DeliveryPlaceBlock = x.DeliveryPlaceBlock,
				DeliveryPlaceBP = x.DeliveryPlaceBP,
				DeliveryPlaceBuilding = x.DeliveryPlaceBuilding,
				DeliveryPlaceCity = x.DeliveryPlaceCity,
				DeliveryPlaceCNPJ = x.DeliveryPlaceCNPJ,
				DeliveryPlaceCountry = x.DeliveryPlaceCountry,
				DeliveryPlaceCounty = x.DeliveryPlaceCounty,
				DeliveryPlaceCPF = x.DeliveryPlaceCPF,
				DeliveryPlaceDepartureDate = x.DeliveryPlaceDepartureDate,
				DeliveryPlaceEMail = x.DeliveryPlaceEMail,
				DeliveryPlacePhone = x.DeliveryPlacePhone,
				DeliveryPlaceState = x.DeliveryPlaceState,
				DeliveryPlaceStreet = x.DeliveryPlaceStreet,
				DeliveryPlaceStreetNo = x.DeliveryPlaceStreetNo,
				DeliveryPlaceZip = x.DeliveryPlaceZip,
				GoodsIssuePlaceBlock = x.GoodsIssuePlaceBlock,
				GoodsIssuePlaceBP = x.GoodsIssuePlaceBP,
				GoodsIssuePlaceBuilding = x.GoodsIssuePlaceBuilding,
				GoodsIssuePlaceCity = x.GoodsIssuePlaceCity,
				GoodsIssuePlaceCNPJ = x.GoodsIssuePlaceCNPJ,
				GoodsIssuePlaceCountry = x.GoodsIssuePlaceCountry,
				GoodsIssuePlaceCounty = x.GoodsIssuePlaceCounty,
				GoodsIssuePlaceCPF = x.GoodsIssuePlaceCPF,
				GoodsIssuePlaceDepartureDate = x.GoodsIssuePlaceDepartureDate,
				GoodsIssuePlaceEMail = x.GoodsIssuePlaceEMail,
				GoodsIssuePlacePhone = x.GoodsIssuePlacePhone,
				GoodsIssuePlaceState = x.GoodsIssuePlaceState,
				GoodsIssuePlaceStreet = x.GoodsIssuePlaceStreet,
				GoodsIssuePlaceStreetNo = x.GoodsIssuePlaceStreetNo,
				GoodsIssuePlaceZip = x.GoodsIssuePlaceZip,
				PlaceOfSupply = x.PlaceOfSupply,
				PurchasePlaceOfSupply = x.PurchasePlaceOfSupply,
				ShipToAddress2 = x.ShipToAddress2,
				ShipToAddress3 = x.ShipToAddress3,
				ShipToAddressType = x.ShipToAddressType,
				ShipToBlock = x.ShipToBlock,
				ShipToBuilding = x.ShipToBuilding,
				ShipToCity = x.ShipToCity,
				ShipToCountry = x.ShipToCountry,
				ShipToCounty = x.ShipToCounty,
				ShipToGlobalLocationNumber = x.ShipToGlobalLocationNumber,
				ShipToState = x.ShipToState,
				ShipToStreet = x.ShipToStreet,
				ShipToStreetNo = x.ShipToStreetNo,
				ShipToZipCode = x.ShipToZipCode,
			};
		}
		
		public virtual BillOfExchange ToSql(Api.Domain.Common.BillOfExchange x)
		{
			return new BillOfExchange {

			};
		}
		
		public virtual CashFlowAssignment ToSql(Api.Domain.Common.CashFlowAssignment x)
		{
			return new CashFlowAssignment {
				AmountLC = x.AmountLC,
				PaymentMeans = x.PaymentMeans,
			};
		}
		
		public virtual DocumentInstallment ToSql(Api.Domain.Common.DocumentInstallment x)
		{
			return new DocumentInstallment {
				Percentage = x.Percentage,
				Total = x.Total,
				DunningLevel = x.DunningLevel,
				InstallmentId = x.InstallmentId,
				LastDunningDate = x.LastDunningDate,
				PaymentOrdered = x.PaymentOrdered,
				TotalFC = x.TotalFC,
			};
		}
		
		public virtual DocumentLine ToSql(Api.Domain.Common.DocumentLine x)
		{
			return new DocumentLine {
				ActualDeliveryDate = x.ActualDeliveryDate,
				ShipDate = x.ShipDate,
				AppliedTax = x.AppliedTax,
				AppliedTaxFC = x.AppliedTaxFC,
				AppliedTaxSC = x.AppliedTaxSC,
				BaseOpenQuantity = x.BaseOpenQuantity,
				CommisionPercent = x.CommisionPercent,
				CorrInvAmountToDiffAcct = x.CorrInvAmountToDiffAcct,
				CorrInvAmountToStock = x.CorrInvAmountToStock,
				CtrSealQty = x.CtrSealQty,
				DefectAndBreakup = x.DefectAndBreakup,
				DiscountPercent = x.DiscountPercent,
				EqualizationTaxPercent = x.EqualizationTaxPercent,
				ExciseAmount = x.ExciseAmount,
				ExternalCalcTaxAmount = x.ExternalCalcTaxAmount,
				ExternalCalcTaxAmountFC = x.ExternalCalcTaxAmountFC,
				ExternalCalcTaxAmountSC = x.ExternalCalcTaxAmountSC,
				ExternalCalcTaxRate = x.ExternalCalcTaxRate,
				Factor1 = x.Factor1,
				Factor2 = x.Factor2,
				Factor3 = x.Factor3,
				Factor4 = x.Factor4,
				GrossBuyPrice = x.GrossBuyPrice,
				GrossPrice = x.GrossPrice,
				GrossProfit = x.GrossProfit,
				GrossProfitFC = x.GrossProfitFC,
				GrossProfitSC = x.GrossProfitSC,
				GrossProfitTotalBasePrice = x.GrossProfitTotalBasePrice,
				GrossTotal = x.GrossTotal,
				GrossTotalFC = x.GrossTotalFC,
				GrossTotalSC = x.GrossTotalSC,
				Height1 = x.Height1,
				Height2 = x.Height2,
				InventoryQuantity = x.InventoryQuantity,
				LastBuyDistributeSum = x.LastBuyDistributeSum,
				LastBuyDistributeSumFc = x.LastBuyDistributeSumFc,
				LastBuyDistributeSumSc = x.LastBuyDistributeSumSc,
				LastBuyInmPrice = x.LastBuyInmPrice,
				Lengh1 = x.Lengh1,
				Lengh2 = x.Lengh2,
				LineTotal = x.LineTotal,
				NetTaxAmount = x.NetTaxAmount,
				NetTaxAmountFC = x.NetTaxAmountFC,
				NetTaxAmountSC = x.NetTaxAmountSC,
				OpenAmount = x.OpenAmount,
				OpenAmountFC = x.OpenAmountFC,
				OpenAmountSC = x.OpenAmountSC,
				PackageQuantity = x.PackageQuantity,
				PickQuantity = x.PickQuantity,
				Price = x.Price,
				PriceAfterVAT = x.PriceAfterVAT,
				Quantity = x.Quantity,
				Rate = x.Rate,
				RemainingOpenInventoryQuantity = x.RemainingOpenInventoryQuantity,
				RemainingOpenQuantity = x.RemainingOpenQuantity,
				RequiredQuantity = x.RequiredQuantity,
				RetirementAPC = x.RetirementAPC,
				RetirementQuantity = x.RetirementQuantity,
				RowTotalFC = x.RowTotalFC,
				RowTotalSC = x.RowTotalSC,
				Shortages = x.Shortages,
				StockDistributesum = x.StockDistributesum,
				StockDistributesumForeign = x.StockDistributesumForeign,
				StockDistributesumSystem = x.StockDistributesumSystem,
				StockInmPrice = x.StockInmPrice,
				Surpluses = x.Surpluses,
				TaxBeforeDPM = x.TaxBeforeDPM,
				TaxBeforeDPMFC = x.TaxBeforeDPMFC,
				TaxBeforeDPMSC = x.TaxBeforeDPMSC,
				TaxPercentagePerRow = x.TaxPercentagePerRow,
				TaxPerUnit = x.TaxPerUnit,
				TaxTotal = x.TaxTotal,
				TotalEqualizationTax = x.TotalEqualizationTax,
				TotalEqualizationTaxFC = x.TotalEqualizationTaxFC,
				TotalEqualizationTaxSC = x.TotalEqualizationTaxSC,
				TotalInclTax = x.TotalInclTax,
				UnitPrice = x.UnitPrice,
				UnitsOfMeasurment = x.UnitsOfMeasurment,
				Volume = x.Volume,
				Weight1 = x.Weight1,
				Weight2 = x.Weight2,
				WeightOfRecycledPlastic = x.WeightOfRecycledPlastic,
				Width1 = x.Width1,
				Width2 = x.Width2,
				BaseType = x.BaseType,
				CESTCode = x.CESTCode,
				CommodityClassification = x.CommodityClassification,
				DocEntry = x.DocEntry,
				GrossBase = x.GrossBase,
				Incoterms = x.Incoterms,
				LineNum = x.LineNum,
				NCMCode = x.NCMCode,
				SalesPersonCode = x.SalesPersonCode,
				ShippingMethod = x.ShippingMethod,
				StandardItemIdentification = x.StandardItemIdentification,
				TransportMode = x.TransportMode,
				UoMEntry = x.UoMEntry,
				VisualOrder = x.VisualOrder,
				VolumeUnit = x.VolumeUnit,
				AccountCode = x.AccountCode,
				ActualBaseEntry = x.ActualBaseEntry,
				ActualBaseLine = x.ActualBaseLine,
				Address = x.Address,
				AgreementNo = x.AgreementNo,
				AgreementRowNumber = x.AgreementRowNumber,
				BackOrder = x.BackOrder,
				BarCode = x.BarCode,
				BaseEntry = x.BaseEntry,
				BaseLine = x.BaseLine,
				CFOPCode = x.CFOPCode,
				ChangeAssemlyBoMWarehouse = x.ChangeAssemlyBoMWarehouse,
				ChangeInventoryQuantityIndependently = x.ChangeInventoryQuantityIndependently,
				Cig = x.Cig,
				CNJPMan = x.CNJPMan,
				COGSAccountCode = x.COGSAccountCode,
				COGSCostingCode = x.COGSCostingCode,
				COGSCostingCode2 = x.COGSCostingCode2,
				COGSCostingCode3 = x.COGSCostingCode3,
				COGSCostingCode4 = x.COGSCostingCode4,
				COGSCostingCode5 = x.COGSCostingCode5,
				ConsiderQuantity = x.ConsiderQuantity,
				ConsumerSalesForecast = x.ConsumerSalesForecast,
				CorrectionInvoiceItem = x.CorrectionInvoiceItem,
				CostingCode = x.CostingCode,
				CostingCode2 = x.CostingCode2,
				CostingCode3 = x.CostingCode3,
				CostingCode4 = x.CostingCode4,
				CostingCode5 = x.CostingCode5,
				CountryOrg = x.CountryOrg,
				CreditOriginCode = x.CreditOriginCode,
				CSTCode = x.CSTCode,
				CSTforCOFINS = x.CSTforCOFINS,
				CSTforIPI = x.CSTforIPI,
				CSTforPIS = x.CSTforPIS,
				Cup = x.Cup,
				Currency = x.Currency,
				CUSplit = x.CUSplit,
				DeferredTax = x.DeferredTax,
				DestinationCountryForImport = x.DestinationCountryForImport,
				DestinationRegionForImport = x.DestinationRegionForImport,
				DistributeExpense = x.DistributeExpense,
				ExLineNo = x.ExLineNo,
				ExpenseOperationType = x.ExpenseOperationType,
				ExpenseType = x.ExpenseType,
				FederalTaxID = x.FederalTaxID,
				FreeOfChargeBP = x.FreeOfChargeBP,
				FreeText = x.FreeText,
				Height2Unit = x.Height2Unit,
				Hight1Unit = x.Hight1Unit,
				HSNEntry = x.HSNEntry,
				IndEscala = x.IndEscala,
				ItemCode = x.ItemCode,
				ItemDescription = x.ItemDescription,
				ItemDetails = x.ItemDetails,
				ItemType = x.ItemType,
				LegalText = x.LegalText,
				Lengh1Unit = x.Lengh1Unit,
				Lengh2Unit = x.Lengh2Unit,
				LineStatus = x.LineStatus,
				LineType = x.LineType,
				ListNum = x.ListNum,
				LocationCode = x.LocationCode,
				MeasureUnit = x.MeasureUnit,
				NatureOfTransaction = x.NatureOfTransaction,
				NVECode = x.NVECode,
				OriginalItem = x.OriginalItem,
				OriginCountryForExport = x.OriginCountryForExport,
				OriginRegionForExport = x.OriginRegionForExport,
				OwnerCode = x.OwnerCode,
				ParentLineNum = x.ParentLineNum,
				PartialRetirement = x.PartialRetirement,
				PickListIdNumber = x.PickListIdNumber,
				PickStatus = x.PickStatus,
				PickStatusEx = x.PickStatusEx,
				PlasticPackageExemptionReason = x.PlasticPackageExemptionReason,
				PoItmNum = x.PoItmNum,
				PoNum = x.PoNum,
				POTargetEntry = x.POTargetEntry,
				POTargetNum = x.POTargetNum,
				POTargetRowNum = x.POTargetRowNum,
				PriceSource = x.PriceSource,
				ProjectCode = x.ProjectCode,
				ReceiptNumber = x.ReceiptNumber,
				RecognizedTaxCode = x.RecognizedTaxCode,
				RequiredDate = x.RequiredDate,
				ReverseCharge = x.ReverseCharge,
				SACEntry = x.SACEntry,
				SerialNum = x.SerialNum,
				ShipToCode = x.ShipToCode,
				ShipToDescription = x.ShipToDescription,
				StgDesc = x.StgDesc,
				StgEntry = x.StgEntry,
				StgSeqNum = x.StgSeqNum,
				SupplierCatNum = x.SupplierCatNum,
				SWW = x.SWW,
				TaxCode = x.TaxCode,
				TaxLiable = x.TaxLiable,
				TaxOnly = x.TaxOnly,
				TaxType = x.TaxType,
				Text = x.Text,
				ThirdParty = x.ThirdParty,
				TransactionType = x.TransactionType,
				TreeType = x.TreeType,
				UFFiscalBenefitCode = x.UFFiscalBenefitCode,
				UnencumberedReason = x.UnencumberedReason,
				UoMCode = x.UoMCode,
				Usage = x.Usage,
				UseBaseUnits = x.UseBaseUnits,
				VatGroup = x.VatGroup,
				VendorNum = x.VendorNum,
				WarehouseCode = x.WarehouseCode,
				Weight1Unit = x.Weight1Unit,
				Weight2Unit = x.Weight2Unit,
				Width1Unit = x.Width1Unit,
				Width2Unit = x.Width2Unit,
				WithoutInventoryMovement = x.WithoutInventoryMovement,
				WTLiable = x.WTLiable,
			};
		}
		
		public virtual DownPaymentsToDraw ToSql(Api.Domain.Common.DownPaymentsToDraw x)
		{
			return new DownPaymentsToDraw {
				DocEntry = x.DocEntry,
				DocInternalID = x.DocInternalID,
				DocNumber = x.DocNumber,
				RowNum = x.RowNum,
				DueDate = x.DueDate,
				PostingDate = x.PostingDate,
				AmountToDraw = x.AmountToDraw,
				AmountToDrawSC = x.AmountToDrawSC,
				GrossAmountToDraw = x.GrossAmountToDraw,
				GrossAmountToDrawFC = x.GrossAmountToDrawFC,
				GrossAmountToDrawSC = x.GrossAmountToDrawSC,
				Tax = x.Tax,
				TaxFC = x.TaxFC,
				TaxSC = x.TaxSC,
				AmountToDrawFC = x.AmountToDrawFC,
				Details = x.Details,
				DownPaymentType = x.DownPaymentType,
				IsGrossLine = x.IsGrossLine,
				Name = x.Name,
			};
		}
		
		public virtual DownPaymentsToDrawDetail ToSql(Api.Domain.Common.DownPaymentsToDrawDetail x)
		{
			return new DownPaymentsToDrawDetail {
				DocEntry = x.DocEntry,
				DocInternalID = x.DocInternalID,
				RowNum = x.RowNum,
				SeqNum = x.SeqNum,
				AmountToDraw = x.AmountToDraw,
				AmountToDrawSC = x.AmountToDrawSC,
				GrossAmountToDraw = x.GrossAmountToDraw,
				GrossAmountToDrawFC = x.GrossAmountToDrawFC,
				GrossAmountToDrawSC = x.GrossAmountToDrawSC,
				Tax = x.Tax,
				TaxSC = x.TaxSC,
				VatPercent = x.VatPercent,
				AmountToDrawFC = x.AmountToDrawFC,
				IsGrossLine = x.IsGrossLine,
				LineType = x.LineType,
				TaxAdjust = x.TaxAdjust,
				TaxFC = x.TaxFC,
				VatGroupCode = x.VatGroupCode,
			};
		}
		
		public virtual EWayBillDetail ToSql(Api.Domain.Common.EWayBillDetails x)
		{
			return new EWayBillDetail {

			};
		}
		
		public virtual LineTaxJurisdiction ToSql(Api.Domain.Common.LineTaxJurisdiction x)
		{
			return new LineTaxJurisdiction {
				DocEntry = x.DocEntry,
				JurisdictionType = x.JurisdictionType,
				LineNumber = x.LineNumber,
				RowSequence = x.RowSequence,
				BaseSum = x.BaseSum,
				ExternalCalcTaxAmount = x.ExternalCalcTaxAmount,
				ExternalCalcTaxAmountFC = x.ExternalCalcTaxAmountFC,
				ExternalCalcTaxAmountSC = x.ExternalCalcTaxAmountSC,
				ExternalCalcTaxRate = x.ExternalCalcTaxRate,
				NonDeductiblePercent = x.NonDeductiblePercent,
				TaxAmount = x.TaxAmount,
				TaxAmountFC = x.TaxAmountFC,
				TaxAmountSC = x.TaxAmountSC,
				TaxRate = x.TaxRate,
				Exempt = x.Exempt,
				JurisdictionCode = x.JurisdictionCode,
				TaxInPrice = x.TaxInPrice,
				TaxOnReserveInvoice = x.TaxOnReserveInvoice,
				Unencumbered = x.Unencumbered,
			};
		}
		
		public virtual PaymentDocumentReferencesCollection ToSql(Api.Domain.Common.PaymentDocumentReferencesCollection x)
		{
			return new PaymentDocumentReferencesCollection {
				IssueDate = x.IssueDate,
				DocEntry = x.DocEntry,
				LineNumber = x.LineNumber,
				ReferencedDocEntry = x.ReferencedDocEntry,
				ReferencedDocNumber = x.ReferencedDocNumber,
				ExternalReferencedDocNumber = x.ExternalReferencedDocNumber,
				ReferencedObjectType = x.ReferencedObjectType,
				Remark = x.Remark,
			};
		}

		public virtual PurchaseTaxInvoiceLine ToSql(Api.Domain.Common.PurchaseTaxInvoiceLine x)
		{
			return new PurchaseTaxInvoiceLine {
				RefEntry1 = x.RefEntry1,
			};
		}
		
		public virtual PurchaseTaxInvoiceOperationCode ToSql(Api.Domain.Common.PurchaseTaxInvoiceOperationCode x)
		{
			return new PurchaseTaxInvoiceOperationCode {
				OpCode = x.OpCode,
			};
		}
		
		public virtual SalesTaxInvoiceLine ToSql(Api.Domain.Common.SalesTaxInvoiceLine x)
		{
			return new SalesTaxInvoiceLine {
				RefEntry1 = x.RefEntry1,
			};
		}
		
		public virtual SalesTaxInvoiceOperationCode ToSql(Api.Domain.Common.SalesTaxInvoiceOperationCode x)
		{
			return new SalesTaxInvoiceOperationCode {
				OpCode = x.OpCode,
			};
		}
		
		public virtual TaxExtension ToSql(Api.Domain.Common.TaxExtension x)
		{
			return new TaxExtension {
				DocEntry = x.DocEntry,
				BoEValue = x.BoEValue,
				GrossWeight = x.GrossWeight,
				NetWeight = x.NetWeight,
				BillOfEntryDate = x.BillOfEntryDate,
				BillOfEntryNo = x.BillOfEntryNo,
				BlockB = x.BlockB,
				BlockS = x.BlockS,
				Brand = x.Brand,
				BuildingB = x.BuildingB,
				BuildingS = x.BuildingS,
				Carrier = x.Carrier,
				CityB = x.CityB,
				CityS = x.CityS,
				ClaimRefund = x.ClaimRefund,
				CountryB = x.CountryB,
				CountryS = x.CountryS,
				County = x.County,
				CountyB = x.CountyB,
				CountyS = x.CountyS,
				DifferentialOfTaxRate = x.DifferentialOfTaxRate,
				GlobalLocationNumberB = x.GlobalLocationNumberB,
				GlobalLocationNumberS = x.GlobalLocationNumberS,
				ImportOrExport = x.ImportOrExport,
				ImportOrExportType = x.ImportOrExportType,
				Incoterms = x.Incoterms,
				IsIGSTAccount = x.IsIGSTAccount,
				MainUsage = x.MainUsage,
				NFRef = x.NFRef,
				OriginalBillOfEntryDate = x.OriginalBillOfEntryDate,
				OriginalBillOfEntryNo = x.OriginalBillOfEntryNo,
				PackDescription = x.PackDescription,
				PackQuantity = x.PackQuantity,
				PortCode = x.PortCode,
				ShipUnitNo = x.ShipUnitNo,
				State = x.State,
				StateB = x.StateB,
				StateS = x.StateS,
				StreetB = x.StreetB,
				StreetS = x.StreetS,
				TaxId0 = x.TaxId0,
				TaxId1 = x.TaxId1,
				TaxId12 = x.TaxId12,
				TaxId13 = x.TaxId13,
				TaxId14 = x.TaxId14,
				TaxId2 = x.TaxId2,
				TaxId3 = x.TaxId3,
				TaxId4 = x.TaxId4,
				TaxId5 = x.TaxId5,
				TaxId6 = x.TaxId6,
				TaxId7 = x.TaxId7,
				TaxId8 = x.TaxId8,
				TaxId9 = x.TaxId9,
				Vehicle = x.Vehicle,
				VehicleState = x.VehicleState,
				ZipCodeB = x.ZipCodeB,
				ZipCodeS = x.ZipCodeS,
			};
		}
	}
}