using System.Collections.Generic;

namespace Sap.Api.Domain.VendorPayments
{
	public partial class VendorPaymentRequest : BaseRequest
	{
		public const string ACTION = "VendorPayments";
		#region Fields
		public string DocNum;
		public string DocType;
		public string HandWritten;
		public string Printed;
		public string DocDate;
		public string CardCode;
		public string CardName;
		public string Address;
		public string CashAccount;
		public string DocCurrency;
		public string CashSum;
		public string CheckAccount;
		public string TransferAccount;
		public string TransferSum;
		public string TransferDate;
		public string TransferReference;
		public string LocalCurrency;
		public string DocRate;
		public string Reference1;
		public string Reference2;
		public string CounterReference;
		public string Remarks;
		public string JournalRemarks;
		public string SplitTransaction;
		public string ContactPersonCode;
		public string ApplyVAT;
		public string TaxDate;
		public string Series;
		public string BankCode;
		public string BankAccount;
		public string DiscountPercent;
		public string ProjectCode;
		public string CurrencyIsLocal;
		public string DeductionPercent;
		public string DeductionSum;
		public string CashSumFC;
		public string CashSumSys;
		public string BoeAccount;
		public string BillOfExchangeAmount;
		public string BillofExchangeStatus;
		public string BillOfExchangeAmountFC;
		public string BillOfExchangeAmountSC;
		public string BillOfExchangeAgent;
		public string WTCode;
		public string WTAmount;
		public string WTAmountFC;
		public string WTAmountSC;
		public string WTAccount;
		public string WTTaxableAmount;
		public string Proforma;
		public string PayToBankCode;
		public string PayToBankBranch;
		public string PayToBankAccountNo;
		public string PayToCode;
		public string PayToBankCountry;
		public string IsPayToBank;
		public string DocEntry;
		public string PaymentPriority;
		public string TaxGroup;
		public string BankChargeAmount;
		public string BankChargeAmountInFC;
		public string BankChargeAmountInSC;
		public string UnderOverpaymentdifference;
		public string UnderOverpaymentdiffSC;
		public string WtBaseSum;
		public string WtBaseSumFC;
		public string WtBaseSumSC;
		public string VatDate;
		public string TransactionCode;
		public string PaymentType;
		public string TransferRealAmount;
		public string DocObjectCode;
		public string DocTypte;
		public string DueDate;
		public string LocationCode;
		public string Cancelled;
		public string ControlAccount;
		public string UnderOverpaymentdiffFC;
		public string AuthorizationStatus;
		public string BPLID;
		public string BPLName;
		public string VATRegNum;
		public string BlanketAgreement;
		public string PaymentByWTCertif;
		public string Cig;
		public string Cup;
		public string AttachmentEntry;
		public string SignatureInputMessage;
		public string SignatureDigest;
		public string CertificationNumber;
		public string PrivateKeyVersion;
		public string EDocExportFormat;
		public string ElecCommStatus;
		public string ElecCommMessage;
		public string SplitVendorCreditRow;
		public IList<PaymentCheck> PaymentChecks;
		public IList<PaymentInvoice> PaymentInvoices;
		public IList<object> PaymentCreditCards;
		public IList<object> PaymentAccounts;
		public IList<object> PaymentDocumentReferencesCollection;
		public BillOfExchange BillOfExchange;
		public IList<object> WithholdingTaxCertificatesCollection;
		public IList<object> ElectronicProtocols;
		public IList<object> CashFlowAssignments;
		public IList<object> PaymentsApprovalRequests;
		public IList<object> WithholdingTaxDataWTXCollection;
		#endregion

		public VendorPaymentRequest()
		{
			BillOfExchange = new BillOfExchange();
			CashFlowAssignments = new List<object>();
			ElectronicProtocols = new List<object>();
			PaymentAccounts = new List<object>();
			PaymentChecks = new List<PaymentCheck>();
			PaymentCreditCards = new List<object>();
			PaymentDocumentReferencesCollection = new List<object>();
			PaymentInvoices = new List<PaymentInvoice>();
			PaymentsApprovalRequests = new List<object>();
			WithholdingTaxCertificatesCollection = new List<object>();
			WithholdingTaxDataWTXCollection = new List<object>();
		}

		public VendorPaymentRequest(string docEntry)
		{
			DocEntry = docEntry;
			BillOfExchange = new BillOfExchange();
			CashFlowAssignments = new List<object>();
			ElectronicProtocols = new List<object>();
			PaymentAccounts = new List<object>();
			PaymentChecks = new List<PaymentCheck>();
			PaymentCreditCards = new List<object>();
			PaymentDocumentReferencesCollection = new List<object>();
			PaymentInvoices = new List<PaymentInvoice>();
			PaymentsApprovalRequests = new List<object>();
			WithholdingTaxCertificatesCollection = new List<object>();
			WithholdingTaxDataWTXCollection = new List<object>();
		}

		public VendorPaymentRequest(VendorPayment x)
		{
			DocNum = x.DocNum;
			DocType = x.DocType;
			HandWritten = x.HandWritten;
			Printed = x.Printed;
			DocDate = x.DocDate;
			CardCode = x.CardCode;
			CardName = x.CardName;
			Address = x.Address;
			CashAccount = x.CashAccount;
			DocCurrency = x.DocCurrency;
			CashSum = x.CashSum;
			CheckAccount = x.CheckAccount;
			TransferAccount = x.TransferAccount;
			TransferSum = x.TransferSum;
			TransferDate = x.TransferDate;
			TransferReference = x.TransferReference;
			LocalCurrency = x.LocalCurrency;
			DocRate = x.DocRate;
			Reference1 = x.Reference1;
			Reference2 = x.Reference2;
			CounterReference = x.CounterReference;
			Remarks = x.Remarks;
			JournalRemarks = x.JournalRemarks;
			SplitTransaction = x.SplitTransaction;
			ContactPersonCode = x.ContactPersonCode;
			ApplyVAT = x.ApplyVAT;
			TaxDate = x.TaxDate;
			Series = x.Series;
			BankCode = x.BankCode;
			BankAccount = x.BankAccount;
			DiscountPercent = x.DiscountPercent;
			ProjectCode = x.ProjectCode;
			CurrencyIsLocal = x.CurrencyIsLocal;
			DeductionPercent = x.DeductionPercent;
			DeductionSum = x.DeductionSum;
			CashSumFC = x.CashSumFC;
			CashSumSys = x.CashSumSys;
			BoeAccount = x.BoeAccount;
			BillOfExchangeAmount = x.BillOfExchangeAmount;
			BillofExchangeStatus = x.BillofExchangeStatus;
			BillOfExchangeAmountFC = x.BillOfExchangeAmountFC;
			BillOfExchangeAmountSC = x.BillOfExchangeAmountSC;
			BillOfExchangeAgent = x.BillOfExchangeAgent;
			WTCode = x.WTCode;
			WTAmount = x.WTAmount;
			WTAmountFC = x.WTAmountFC;
			WTAmountSC = x.WTAmountSC;
			WTAccount = x.WTAccount;
			WTTaxableAmount = x.WTTaxableAmount;
			Proforma = x.Proforma;
			PayToBankCode = x.PayToBankCode;
			PayToBankBranch = x.PayToBankBranch;
			PayToBankAccountNo = x.PayToBankAccountNo;
			PayToCode = x.PayToCode;
			PayToBankCountry = x.PayToBankCountry;
			IsPayToBank = x.IsPayToBank;
			DocEntry = x.DocEntry;
			PaymentPriority = x.PaymentPriority;
			TaxGroup = x.TaxGroup;
			BankChargeAmount = x.BankChargeAmount;
			BankChargeAmountInFC = x.BankChargeAmountInFC;
			BankChargeAmountInSC = x.BankChargeAmountInSC;
			UnderOverpaymentdifference = x.UnderOverpaymentdifference;
			UnderOverpaymentdiffSC = x.UnderOverpaymentdiffSC;
			WtBaseSum = x.WtBaseSum;
			WtBaseSumFC = x.WtBaseSumFC;
			WtBaseSumSC = x.WtBaseSumSC;
			VatDate = x.VatDate;
			TransactionCode = x.TransactionCode;
			PaymentType = x.PaymentType;
			TransferRealAmount = x.TransferRealAmount;
			DocObjectCode = x.DocObjectCode;
			DocTypte = x.DocTypte;
			DueDate = x.DueDate;
			LocationCode = x.LocationCode;
			Cancelled = x.Cancelled;
			ControlAccount = x.ControlAccount;
			UnderOverpaymentdiffFC = x.UnderOverpaymentdiffFC;
			AuthorizationStatus = x.AuthorizationStatus;
			BPLID = x.BPLID;
			BPLName = x.BPLName;
			VATRegNum = x.VATRegNum;
			BlanketAgreement = x.BlanketAgreement;
			PaymentByWTCertif = x.PaymentByWTCertif;
			Cig = x.Cig;
			Cup = x.Cup;
			AttachmentEntry = x.AttachmentEntry;
			SignatureInputMessage = x.SignatureInputMessage;
			SignatureDigest = x.SignatureDigest;
			CertificationNumber = x.CertificationNumber;
			PrivateKeyVersion = x.PrivateKeyVersion;
			EDocExportFormat = x.EDocExportFormat;
			ElecCommStatus = x.ElecCommStatus;
			ElecCommMessage = x.ElecCommMessage;
			SplitVendorCreditRow = x.SplitVendorCreditRow;
			PaymentChecks = x.PaymentChecks;
			PaymentInvoices = x.PaymentInvoices;
			PaymentCreditCards = x.PaymentCreditCards;
			PaymentAccounts = x.PaymentAccounts;
			PaymentDocumentReferencesCollection = x.PaymentDocumentReferencesCollection;
			BillOfExchange = x.BillOfExchange;
			WithholdingTaxCertificatesCollection = x.WithholdingTaxCertificatesCollection;
			ElectronicProtocols = x.ElectronicProtocols;
			CashFlowAssignments = x.CashFlowAssignments;
			PaymentsApprovalRequests = x.PaymentsApprovalRequests;
			WithholdingTaxDataWTXCollection = x.WithholdingTaxDataWTXCollection;
		}
	}
}