using ScarletWitch.Sap_ArrowAndBranchWinery.Domain;

namespace ApiToScarletWitchMapper
{
	public partial class Mapper
	{
		public virtual HouseBankAccount ToSql(Sap.Api.Domain.HouseBankAccounts.HouseBankAccount x)
		{
			return new HouseBankAccount {
				AbsoluteEntry = x.AbsoluteEntry,
				BankKey = x.BankKey,
				IncomingPaymentSeries = x.IncomingPaymentSeries,
				ISRType = x.ISRType,
				JournalEntrySeries = x.JournalEntrySeries,
				OutgoingPaymentSeries = x.OutgoingPaymentSeries,
				DiscountLimit = x.DiscountLimit,
				MaxAmountofBillofExchan = x.MaxAmountofBillofExchan,
				MinAmountofBillofExchang = x.MinAmountofBillofExchang,
				AccNo = x.AccNo,
				AccountCheckDigit = x.AccountCheckDigit,
				AccountName = x.AccountName,
				AddressType = x.AddressType,
				AgreementNumber = x.AgreementNumber,
				BankCode = x.BankCode,
				BankonCollection = x.BankonCollection,
				BankonDiscounted = x.BankonDiscounted,
				BICSwiftCode = x.BICSwiftCode,
				BISR = x.BISR,
				Block = x.Block,
				Branch = x.Branch,
				BranchCheckDigit = x.BranchCheckDigit,
				Building = x.Building,
				City = x.City,
				CollectionCode = x.CollectionCode,
				ControlKey = x.ControlKey,
				Country = x.Country,
				County = x.County,
				CustomerIdNumber = x.CustomerIdNumber,
				DaysInAdvance = x.DaysInAdvance,
				DebtofDiscountedBillofExc = x.DebtofDiscountedBillofExc,
				DiscountAccount = x.DiscountAccount,
				DSC1STREETALIAS = x.DSC1STREETALIAS,
				ECheck = x.ECheck,
				FileSeqNextNumber = x.FileSeqNextNumber,
				FineAccount = x.FineAccount,
				GLAccount = x.GLAccount,
				GLInterimAccount = x.GLInterimAccount,
				IBAN = x.IBAN,
				ImportFileName = x.ImportFileName,
				InterestAccount = x.InterestAccount,
				IOFTaxAccount = x.IOFTaxAccount,
				ISRBillerID = x.ISRBillerID,
				LockChecksPrinting = x.LockChecksPrinting,
				MaximumLines = x.MaximumLines,
				NextCheckNo = x.NextCheckNo,
				NoValidationForStartingEndingBal = x.NoValidationForStartingEndingBal,
				OtherExpensesAccount = x.OtherExpensesAccount,
				OtherIncomesAccount = x.OtherIncomesAccount,
				OurNumber = x.OurNumber,
				PrintOn = x.PrintOn,
				RetornoFileName = x.RetornoFileName,
				ServiceFeeAccount = x.ServiceFeeAccount,
				State = x.State,
				StreetNo = x.StreetNo,
				TemplateName = x.TemplateName,
				ToleranceDays = x.ToleranceDays,
				UserNo1 = x.UserNo1,
				UserNo2 = x.UserNo2,
				UserNo3 = x.UserNo3,
				UserNo4 = x.UserNo4,
				ZipCode = x.ZipCode,
			};
		}
	}
}