using ScarletWitch.Sap_RareCoinWholesalers.Domain;

namespace Sap.ApiToScarRcwMapper
{
	public partial class Mapper
	{
		public virtual PaymentCheck ToSql(Api.Domain.VendorPayments.PaymentCheck x)
		{
			return new PaymentCheck {
				DocEntry = x.DocEntry,
				LineNum = x.LineNum,
				DueDate = x.DueDate,
				CheckNumber = x.CheckNumber,
				BankCode = x.BankCode,
				Branch = x.Branch,
				AccounttNum = x.AccounttNum,
				Details = x.Details,
				Trnsfrable = x.Trnsfrable,
				CheckSum = x.CheckSum,
				Currency = x.Currency,
				CountryCode = x.CountryCode,
				CheckAbsEntry = x.CheckAbsEntry,
				CheckAccount = x.CheckAccount,
				ManualCheck = x.ManualCheck,
				FiscalID = x.FiscalID,
				OriginallyIssuedBy = x.OriginallyIssuedBy,
				Endorse = x.Endorse,
				EndorsableCheckNo = x.EndorsableCheckNo,
				ECheck = x.ECheck,
			};
		}

		public virtual PaymentInvoice ToSql(Api.Domain.VendorPayments.PaymentInvoice x)
		{
			return new PaymentInvoice {
				VendorPaymentDocEntry = x.VendorPaymentDocEntry,
				LineNum = x.LineNum,
				DocEntry = x.DocEntry,
				DocNum = x.DocNum,
				SumApplied = x.SumApplied,
				AppliedFC = x.AppliedFC,
				AppliedSys = x.AppliedSys,
				DocRate = x.DocRate,
				DocLine = x.DocLine,
				InvoiceType = x.InvoiceType,
				DiscountPercent = x.DiscountPercent,
				PaidSum = x.PaidSum,
				InstallmentId = x.InstallmentId,
				WitholdingTaxApplied = x.WitholdingTaxApplied,
				WitholdingTaxAppliedFC = x.WitholdingTaxAppliedFC,
				WitholdingTaxAppliedSC = x.WitholdingTaxAppliedSC,
				LinkDate = x.LinkDate,
				DistributionRule = x.DistributionRule,
				DistributionRule2 = x.DistributionRule2,
				DistributionRule3 = x.DistributionRule3,
				DistributionRule4 = x.DistributionRule4,
				DistributionRule5 = x.DistributionRule5,
				TotalDiscount = x.TotalDiscount,
				TotalDiscountFC = x.TotalDiscountFC,
				TotalDiscountSC = x.TotalDiscountSC,
			};
		}

		public virtual VendorPayment ToSql(Api.Domain.VendorPayments.VendorPayment x)
		{
			return new VendorPayment {
				DocNum = x.DocNum,
				DocType = x.DocType,
				HandWritten = x.HandWritten,
				Printed = x.Printed,
				DocDate = x.DocDate,
				CardCode = x.CardCode,
				CardName = x.CardName,
				Address = x.Address,
				CashAccount = x.CashAccount,
				DocCurrency = x.DocCurrency,
				CashSum = x.CashSum,
				CheckAccount = x.CheckAccount,
				TransferAccount = x.TransferAccount,
				TransferSum = x.TransferSum,
				TransferDate = x.TransferDate,
				TransferReference = x.TransferReference,
				LocalCurrency = x.LocalCurrency,
				DocRate = x.DocRate,
				Reference1 = x.Reference1,
				Reference2 = x.Reference2,
				CounterReference = x.CounterReference,
				Remarks = x.Remarks,
				JournalRemarks = x.JournalRemarks,
				SplitTransaction = x.SplitTransaction,
				ContactPersonCode = x.ContactPersonCode,
				ApplyVAT = x.ApplyVAT,
				TaxDate = x.TaxDate,
				Series = x.Series,
				BankCode = x.BankCode,
				BankAccount = x.BankAccount,
				DiscountPercent = x.DiscountPercent,
				ProjectCode = x.ProjectCode,
				CurrencyIsLocal = x.CurrencyIsLocal,
				DeductionPercent = x.DeductionPercent,
				DeductionSum = x.DeductionSum,
				CashSumFC = x.CashSumFC,
				CashSumSys = x.CashSumSys,
				BoeAccount = x.BoeAccount,
				BillOfExchangeAmount = x.BillOfExchangeAmount,
				BillofExchangeStatus = x.BillofExchangeStatus,
				BillOfExchangeAmountFC = x.BillOfExchangeAmountFC,
				BillOfExchangeAmountSC = x.BillOfExchangeAmountSC,
				BillOfExchangeAgent = x.BillOfExchangeAgent,
				WTCode = x.WTCode,
				WTAmount = x.WTAmount,
				WTAmountFC = x.WTAmountFC,
				WTAmountSC = x.WTAmountSC,
				WTAccount = x.WTAccount,
				WTTaxableAmount = x.WTTaxableAmount,
				Proforma = x.Proforma,
				PayToBankCode = x.PayToBankCode,
				PayToBankBranch = x.PayToBankBranch,
				PayToBankAccountNo = x.PayToBankAccountNo,
				PayToCode = x.PayToCode,
				PayToBankCountry = x.PayToBankCountry,
				IsPayToBank = x.IsPayToBank,
				DocEntry = x.DocEntry,
				PaymentPriority = x.PaymentPriority,
				TaxGroup = x.TaxGroup,
				BankChargeAmount = x.BankChargeAmount,
				BankChargeAmountInFC = x.BankChargeAmountInFC,
				BankChargeAmountInSC = x.BankChargeAmountInSC,
				UnderOverpaymentdifference = x.UnderOverpaymentdifference,
				UnderOverpaymentdiffSC = x.UnderOverpaymentdiffSC,
				WtBaseSum = x.WtBaseSum,
				WtBaseSumFC = x.WtBaseSumFC,
				WtBaseSumSC = x.WtBaseSumSC,
				VatDate = x.VatDate,
				TransactionCode = x.TransactionCode,
				PaymentType = x.PaymentType,
				TransferRealAmount = x.TransferRealAmount,
				DocObjectCode = x.DocObjectCode,
				DocTypte = x.DocTypte,
				DueDate = x.DueDate,
				LocationCode = x.LocationCode,
				Cancelled = x.Cancelled,
				ControlAccount = x.ControlAccount,
				UnderOverpaymentdiffFC = x.UnderOverpaymentdiffFC,
				AuthorizationStatus = x.AuthorizationStatus,
				BPLID = x.BPLID,
				BPLName = x.BPLName,
				VATRegNum = x.VATRegNum,
				BlanketAgreement = x.BlanketAgreement,
				PaymentByWTCertif = x.PaymentByWTCertif,
				Cig = x.Cig,
				Cup = x.Cup,
				AttachmentEntry = x.AttachmentEntry,
				SignatureInputMessage = x.SignatureInputMessage,
				SignatureDigest = x.SignatureDigest,
				CertificationNumber = x.CertificationNumber,
				PrivateKeyVersion = x.PrivateKeyVersion,
				EDocExportFormat = x.EDocExportFormat,
				ElecCommStatus = x.ElecCommStatus,
				ElecCommMessage = x.ElecCommMessage,
				SplitVendorCreditRow = x.SplitVendorCreditRow,
			};
		}
	}
}